
[general]
	#Colors must be specified in #RRGGBB format
	"health color values" = ["#FF1313", "#00DA00", "#0C9DF1", "#7713FF", "#B486FF", "#EC8AFB", "#FBD78B", "#03EFEC", "#B7E7FD", "#EDEDED", "#EE8100", "#E5CE00"]
	#Colors must be specified in #RRGGBB format
	"absorption color values" = ["#2020FF", "#FF1313", "#13FF13", "#FFFF13", "#B486FF", "#FF7713"]
	#Description level of text, all shows total health and absorption bars, bars shows number of bars, none doesn't show text
	#Allowed Values: NONE, BARS, ALL
	"show bars" = "ALL"
	#Size of index number
	#Range: 0.0 ~ 1.0
	"text size" = 0.75

